site_name: Things Learned 
site_author: sunflowerno0b
site_url: https://sunflowerno0b.github.io/ATW
nav:
  - Introduction: index.md
  - Markdown Syntax: Markdown Syntax.md
  - Securedrop: Securedrop.md
  - Systems: 
     - Web Services: Web Services.md
     - VS Code: VS Code Install.md
     - Ansible Vault: Ansible Vault.md
     - RSA/config: rsa & config.md
  - Web Application:
     - Introdcution: Intro to Web Applications.md 
  - Resources: Resources.md  
  - Audio: Music.md
plugins:
  - search
  - autolinks
  - git-revision-date-localized:
      type: timeago
  - minify:
      minify_html: true

markdown_extensions:
  - admonition
  - markdown_include.include:
      base_path: docs
  - meta
  - toc:
      #permalink: true
      #baselevel: 2
      toc_depth: 0
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

theme: 
  name: material
  logo: outerspace.png
  features:
    - navigation.instant
  language: en
  palette:
     primary: 'gray'
     accent: 'orange'

extra_css:
  - 'stylesheets/extra.css'
#  - 'stylesheets/links.css'

repo_name: sunflowerno0b/Things-Learned
repo_url: https://github.com/sunflowerno0b/Things-Learned
